### ISSUE TITLE
Unauthorized use of Enigma font software

### ISSUE THREAD

**Issue by JTankard** [nickbramhall/nickbramhall.github.com#1]
I notice that you’re using our copyrighted Enigma font software and redistributing them through this repo.
These fonts, whether licensed or not cannot be put in a public repo. Sorry.

Jeremy Tankard Typography Ltd 
www.typography.net

**Comment by nickbramhall** [comment]
Good afternoon Jeremy,

thank you for your email, however I believe that there may be some
confusion here. I believe you are referring to the *Enigma* font as per
your website:

http://typography.net/fontfamilies/view/67

On my site I am using the *Enigmatic* font designed by Darren Rigby
and downloaded from the following site:

http://www.fontsquirrel.com/fonts/enigmatic

Although the name is similar (and I see in my repo I see that the font name
has been shortened to Enigma), I don't believe that these fonts are related
in any other way.

Please can you review and confirm?

Kind regards,

Nick Bramhall

**Comment by JTankard** [comment]
Thanks Nick

No problem, you’re right.

Regards
Jeremy

> There is now more Enigma
http://typography.net/fontfamilies/view/67 <http://typography.net/fontfamilies/view/67>

Jeremy Tankard Typography Ltd
T +44 (0)1223 47 46 14
typography.net <http://typography.net/>

Twitter @JeremyTankard

DISCLAIMER: This e-mail contains proprietary information some or all 
of which may be legally privileged. It is for the intended recipient only. 
If an addressing or transmission error has misdirected this email, 
please notify the author by replying to this e-mail. If you are not the 
intended recipient you must not use, disclose, distribute, copy, print, 
or rely on this e-mail.

**Comment by nickbramhall** [comment]
Jeremy,

thanks for checking up on that and getting back to me - I'm glad we could
clarify the situation.

Kind regards,

Nick.
